#!/bin/bash

JAMA=lib/Jama-1.0.2.jar
GETOPT=lib/java-getopt-1.0.13.jar
JUNIT=lib/junit.jar
PSST=lib/psst.jar
KD=lib/kd.jar

LIBRARIES="$JAMA:$GETOPT:$JUNIT:$PSST:$KD:build/"

java -Xmx1250MB -Xss1MB -cp $LIBRARIES edu.umbc.cs.maple.$*
